### ISSUE TITLE
Have Problems with go.mod file

### ISSUE THREAD

**Issue by MasterHahn04** [multiplay/go-ts3#32]
When I want compile my Programm without "go.mod"-File it will works fine.
But when I create the "go.mod" and execute the Command "go mod tidy" and then want to execute the Go Programm it didn't work.
![leaderboard](https://user-images.githubusercontent.com/58881529/148575102-184ef4dd-8e5b-4f16-be05-f030e59b806c.PNG)
The Functions then are undefinied

**Comment by stevenh** [comment]
What's the content of your `go.mod` file?

**Comment by stevenh** [comment]
I just created https://github.com/multiplay/go-ts3/releases/tag/v1.0.1 see if that helps.

**Comment by MasterHahn04** [comment]
Thanks a lot. With the Update it works perfectly :)
